version: '2'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - 3306:3306

  web:
    depends_on:
      - db
    build: ./web
    command: /bin/bash
    volumes:
      - ./web:/usr/src/app
    ports:
      - 3000:3000
